language: python
python:
  - 2.7
  - pypy
install:
  - python setup.py develop
  - easy_install . jpcw.formation[test]
script:
  - make test -k
after_success:
  - easy_install coveralls
  - coveralls
